plugin.plugin_configuration.search_api_backend.search_api_solr:
  type: config_object
  label: 'Search API Solr settings'
  mapping:
    retrieve_data:
      type: boolean
      label: 'Retrieve result data from Solr'
    highlight_data:
      type: boolean
      label: 'Highlight retrieved data'
    skip_schema_check:
      type: boolean
      label: 'Skip schema verification'
    site_hash:
      type: boolean
      label: 'Restrict searches to current site'
    domain:
      type: string
      label: 'The targeted content domain'
    connector:
      type: string
      label: 'The connector plugin ID'
    connector_config:
      type: plugin.plugin_configuration.search_api_solr_connector.[%parent.connector]

plugin.plugin_configuration.search_api_backend.search_api_solr_multilingual:
  type: plugin.plugin_configuration.search_api_backend.search_api_solr
  label: 'Search API Multilingual Solr Schema settings'
  mapping:
    sasm_limit_search_page_to_content_language:
      type: boolean
      label: 'Limit to current content language'
    sasm_search_page_include_language_independent:
      type: boolean
      label: 'Include languages independent content in search results'
    sasm_language_unspecific_fallback_on_schema_issues:
      type: boolean
      label: 'Use language undefined fall back'

plugin.plugin_configuration.search_api_backend.search_api_solr_multilingual_managed_schema:
  type: plugin.plugin_configuration.search_api_backend.search_api_solr_multilingual
  label: 'Search API Multilingual Solr Managed Schema settings'

plugin.plugin_configuration.search_api_backend.search_api_solr_any_schema:
  type: plugin.plugin_configuration.search_api_backend.search_api_solr
  label: 'Search API Solr Any Schema settings'
